const COURSES = [
  "Computer Science",
  "Software Engineering",
  "Data Structures and Algorithms",
  "Database Management",
  "Web Development",
  "Mobile App Development",
  "Artigicial Intelligence",
  "Machine Learning",
  "Cybersercurity",
  "Networking",
  "Cloud Computing",
  "Big Data",
  "Blockchain Technology",
  "Internet of Things (IoT)",
  "DevOps",
  "Operating Systems",
  "Human-Computer Interaction",
  "Game Developement",
  "Virtual Reality (VR)",
  "Data Science",
  "Data Analytics",
  "Information Systems",
  "Distributed Systems",
  "Systems Administration",
  "Digital Marketing",
];
export default COURSES;
